
import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm";
import { CONFIG } from "./config.js";
const supabase = createClient(CONFIG.SUPABASE_URL, CONFIG.SUPABASE_ANON_KEY);
const $ = id => document.getElementById(id);
const rupiah = n => "Rp " + Number(n || 0).toLocaleString("id-ID");
const cleanNumber = v => Number(String(v ?? "").replace(/[^\d]/g,"") || 0);
let settings={}, products=[], filtered=[], selected=null, selectedPlan=1, selectedPay="DANA", currentOrder=null;
let waNumber="6287886783807", paymentNumbers={DANA:"087886783807",GoPay:"087886783807",OVO:"087886783807",QRIS:"Scan QRIS"};
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}
async function copy(t){try{await navigator.clipboard.writeText(t);toast("Disalin ✅")}catch{toast("Gagal salin")}}
function parseCSV(text){const rows=[];let row=[],val="",q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c=='"'&&q&&n=='"'){val+='"';i++}else if(c=='"')q=!q;else if(c===","&&!q){row.push(val);val=""}else if((c=="\n"||c=="\r")&&!q){if(c=="\r"&&n=="\n")i++;row.push(val);rows.push(row);row=[];val=""}else val+=c}if(val||row.length){row.push(val);rows.push(row)}const h=(rows.shift()||[]).map(x=>String(x).trim().toLowerCase());return rows.filter(r=>r.some(x=>String(x).trim()!="")).map(r=>{const o={};h.forEach((k,i)=>o[k]=String(r[i]??"").trim());return o})}
async function fetchCSV(url){const r=await fetch(url+(url.includes("?")?"&":"?")+"_="+Date.now());return parseCSV(await r.text())}
function mapProduct(i){return{name:i.nama||i.name||"",slug:i.slug||String(i.nama||"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""),category:(i.kategori||i.category||"lainnya").toLowerCase(),price:cleanNumber(i.harga||i.price||i.harga_1),price1:cleanNumber(i.harga_1||i.harga1||i.harga||i.price),price2:cleanNumber(i.harga_2||i.harga2),price3:cleanNumber(i.harga_3||i.harga3),planText1:i.plan_1_text||i.plan1_text||"1 Bulan",planText2:i.plan_2_text||i.plan2_text||"2 Bulan",planText3:i.plan_3_text||i.plan3_text||"3 Bulan",stock:cleanNumber(i.stok||i.stock||100),label:i.label||"PROMO",status:(i.status||"aktif").toLowerCase(),image:i.gambar||i.image||"gilz.png",desc:i.deskripsi||i.desc||"",rating:i.rating||"4.9",sold:i.terjual||i.sold||"0+",warranty:i.garansi||i.warranty||"Sesuai durasi paket"}}
function getSetting(k,d=""){return settings[k]||d}
function price(p,n){if(n===1)return p.price1||p.price||0;if(n===2)return p.price2||((p.price1||p.price||0)*2);return p.price3||((p.price1||p.price||0)*3)}
function planLabel(){return selectedPlan===1?selected.planText1:selectedPlan===2?selected.planText2:selected.planText3}
function orderId(){const d=new Date();return `GLZ-${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}-${Math.floor(1000+Math.random()*9000)}`}
function statusClass(s){const v=String(s||"").toLowerCase();if(v.includes("selesai")||v.includes("success")||v.includes("berhasil"))return"selesai";if(v.includes("proses"))return"diproses";if(v.includes("batal"))return"batal";return"pending"}
function mask(id){id=String(id||"");return id.length>8?id.slice(0,4)+"******"+id.slice(-4):id}
function isSoldOut(p){return p.stock<=0||["habis","soldout"].includes(p.status)}
function iconHtml(value,fallback){value=value||fallback;if(/\.(png|jpg|jpeg|gif|webp|svg)$/i.test(value))return`<img src="${value}" onerror="this.outerHTML='${fallback}'">`;return value}
function setIcon(id,key,fb){const el=$(id);if(el)el.innerHTML=iconHtml(getSetting(key,fb),fb)}
function setText(id,key,fb){const el=$(id);if(el)el.textContent=getSetting(key,fb)}
function setLinks(){const msg=encodeURIComponent("Halo kak, saya mau tanya produk di GilangStore");const url=`https://wa.me/${waNumber}?text=${msg}`;["waLink","floatWa","bottomWa","drawerWa","maintenanceWa"].forEach(id=>{const e=$(id);if(e)e.href=url})}
async function load(){try{const rows=await fetchCSV(CONFIG.SETTING_CSV_URL);rows.forEach(r=>{const k=(r.nama_setting||r.setting||r.key||"").trim();if(k)settings[k]=r.isi||r.value||""});applySettings()}catch(e){console.warn(e)}try{products=(await fetchCSV(CONFIG.PRODUK_CSV_URL)).map(mapProduct).filter(p=>p.name&&!["nonaktif","off","hidden"].includes(p.status));renderAll();$("sheetStatus").innerHTML=`<b>Google Sheets</b><span>Update ${new Date().toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"})} • ${products.length} produk</span>`;loadRecent()}catch(e){$("sheetStatus").innerHTML="<b>Google Sheets</b><span>Gagal memuat CSV produk</span>";toast("Gagal memuat produk")}}
function applySettings(){document.body.dataset.theme=getSetting("theme","blue");waNumber=getSetting("whatsapp",waNumber).replace(/[^\d]/g,"");paymentNumbers={DANA:getSetting("dana","087886783807"),GoPay:getSetting("gopay","087886783807"),OVO:getSetting("ovo","087886783807"),QRIS:getSetting("qris_text","Scan QRIS")};const name=getSetting("store_name","GilangStore");["storeName","heroTitle","drawerStoreName","maintenanceTitle"].forEach(id=>$(id).textContent=name);document.title=name;$("heroSubtitle").textContent=getSetting("hero_subtitle","Premium apps & digital product");$("runningText").textContent=getSetting("running_text","🔥 Promo Premium Apps • Fast Respond • Garansi Aktif • Order via WhatsApp •");$("adminHours").textContent=getSetting("jam_admin","Fast respond 08.00–22.00 WIB");$("maintenanceText").textContent=getSetting("maintenance_text","Toko sedang maintenance. Silakan kembali lagi nanti.");$("maintenance").classList.toggle("show",getSetting("maintenance","off").toLowerCase()==="on");const banner=$("bannerBox");banner.textContent=getSetting("banner_text","");banner.className="banner "+getSetting("banner_color","warning");banner.classList.toggle("show",getSetting("banner_status","off").toLowerCase()==="on");setIcon("iconMenuHome","icon_menu_home","🏠");setIcon("iconPromo","icon_promo","🔥");setIcon("iconLihatProduk","icon_lihat_produk","🛍️");setIcon("iconHubungiAdmin","icon_hubungi_admin","👤");setIcon("iconFloatingWa","icon_floating_wa","💬");setIcon("drawerBeliIcon","drawer_beli_icon","🛒");setIcon("drawerTopIcon","drawer_top_icon","🏆");setIcon("drawerCekIcon","drawer_cek_icon","🔍");setIcon("drawerRiwayatIcon","drawer_riwayat_icon","🧾");setIcon("drawerGaransiIcon","drawer_garansi_icon","🛡️");setIcon("drawerCaraIcon","drawer_cara_order_icon","📦");setIcon("drawerFaqIcon","drawer_faq_icon","❓");setIcon("drawerTermsIcon","drawer_terms_icon","📜");setIcon("bottomProdukIcon","bottom_produk_icon","🛍️");setIcon("bottomLacakIcon","bottom_lacak_icon","📦");setIcon("bottomChatIcon","bottom_chat_icon","💬");setText("bottomProdukText","bottom_produk_text","Produk");setText("bottomLacakText","bottom_lacak_text","Lacak");setText("bottomChatText","bottom_chat_text","Chat");setText("textLihatProduk","text_lihat_produk","Lihat Produk");setText("textHubungiAdmin","text_hubungi_admin","Hubungi Admin");setLinks();updateCountdown()}
function renderAll(){renderCategories();applyFilter();renderBest();renderHistory()}
function renderCategories(){const cats=["all",...new Set(products.map(p=>p.category))];$("categories").innerHTML=cats.map((c,i)=>`<button class="${i===0?"active":""}" data-cat="${c}">${c==="all"?"Semua":c}</button>`).join("");document.querySelectorAll("#categories button").forEach(btn=>btn.onclick=()=>{document.querySelectorAll("#categories button").forEach(b=>b.classList.remove("active"));btn.classList.add("active");applyFilter()})}
function applyFilter(){const q=$("searchInput").value.toLowerCase();const cat=document.querySelector("#categories .active")?.dataset.cat||"all";filtered=products.filter(p=>(cat==="all"||p.category===cat)&&(p.name.toLowerCase().includes(q)||p.category.includes(q)));$("productCount").textContent=`${filtered.length} produk`;$("products").innerHTML=filtered.map(cardHtml).join("");document.querySelectorAll(".product").forEach(el=>el.onclick=()=>openProduct(el.dataset.slug))}
function cardHtml(p){return`<article class="product ${isSoldOut(p)?"out":""}" data-slug="${p.slug}"><span class="label">${isSoldOut(p)?"HABIS":p.label}</span><span class="stock">${isSoldOut(p)?"Habis":"Stok "+p.stock}</span><img src="${p.image}" onerror="this.src='gilz.png'"><div class="body"><h3>${p.name}</h3><p>⭐ ${p.rating} • Terjual ${p.sold}</p><div class="price">${rupiah(price(p,1))}</div></div></article>`}
function renderBest(){const list=products.slice(0,4);$("bestGrid").innerHTML=list.map(cardHtml).join("");$("bestGrid").querySelectorAll(".product").forEach(el=>el.onclick=()=>openProduct(el.dataset.slug))}
function openProduct(slug){selected=products.find(p=>p.slug===slug);if(!selected)return;if(isSoldOut(selected))return toast("Produk sedang habis");selectedPlan=1;selectedPay="DANA";$("detailImage").src=selected.image;$("detailName").textContent=selected.name;$("detailDesc").textContent=selected.desc;$("detailRating").textContent="⭐ "+selected.rating;$("detailSold").textContent="Terjual "+selected.sold;$("detailStock").textContent="Stok "+selected.stock;$("plan1Text").textContent=selected.planText1;$("plan2Text").textContent=selected.planText2;$("plan3Text").textContent=selected.planText3;$("plan1Price").textContent=rupiah(price(selected,1));$("plan2Price").textContent=rupiah(price(selected,2));$("plan3Price").textContent=rupiah(price(selected,3));$("buyerContact").value="";$("buyerNote").value="";document.querySelectorAll(".plan").forEach((b,i)=>b.classList.toggle("active",i===0));document.querySelectorAll(".pay").forEach((b,i)=>b.classList.toggle("active",i===0));updateSummary();$("detailModal").classList.add("show")}
function updateSummary(){$("summary").innerHTML=`Produk: <b>${selected.name}</b><br>Paket: <b>${planLabel()}</b><br>Payment: <b>${selectedPay}</b><br>Total: <b>${rupiah(price(selected,selectedPlan))}</b>`}
async function checkout(){const contact=$("buyerContact").value.trim();if(!contact)return toast("Isi email/username dulu");const o={order_id:orderId(),produk:selected.name,paket:planLabel(),total:price(selected,selectedPlan),payment:selectedPay,buyer_contact:contact,catatan:$("buyerNote").value.trim(),status:"menunggu_pembayaran"};const {error}=await supabase.from("orders").insert(o);if(error){console.error(error);return toast("Gagal membuat order: "+error.message)}currentOrder=o;saveLocal(o);$("detailModal").classList.remove("show");openPayment(o);loadRecent()}
function openPayment(o){const payNum=o.payment==="QRIS"?"Scan QRIS":(paymentNumbers[o.payment]||"-");$("payInfo").innerHTML=`Order ID: <b>${o.order_id}</b><br>Produk: <b>${o.produk}</b><br>Paket: <b>${o.paket}</b><br>Total: <b>${rupiah(o.total)}</b><br>Payment: <b>${o.payment}</b>`;$("payNumber").value=payNum;$("qrisImg").style.display=o.payment==="QRIS"?"block":"none";const msg=`Halo kak, saya sudah bayar:%0AOrder ID: ${o.order_id}%0AProduk: ${o.produk}%0APaket: ${o.paket}%0ATotal: ${rupiah(o.total)}%0APayment: ${o.payment}`;$("proofWa").href=`https://wa.me/${waNumber}?text=${msg}`;$("payModal").classList.add("show")}
async function markPaid(){if(!currentOrder)return;const {error}=await supabase.from("orders").update({status:"menunggu_konfirmasi"}).eq("order_id",currentOrder.order_id);if(error)return toast("Gagal update: "+error.message);currentOrder.status="menunggu_konfirmasi";saveLocal(currentOrder);toast("Status menunggu konfirmasi ✅");loadRecent()}
async function trackOrder(){const id=$("trackInput").value.trim();if(!id)return toast("Isi Order ID dulu");const {data,error}=await supabase.from("orders").select("*").eq("order_id",id).maybeSingle();if(error)return toast("Gagal cek order");$("trackResult").innerHTML=data?orderDetailHtml(data):"Order ID belum ditemukan."}
async function checkWarranty(){const id=$("warrantyInput").value.trim();if(!id)return toast("Isi Order ID dulu");const {data,error}=await supabase.from("orders").select("*").eq("order_id",id).maybeSingle();if(error)return toast("Gagal cek");$("warrantyResult").innerHTML=data?`${orderDetailHtml(data)}<br>Garansi: <b>Sesuai paket dan bukti pembayaran</b>`:"Order belum ditemukan."}
function orderDetailHtml(o){return`<b>Order ditemukan ✅</b><br>Order ID: <b>${o.order_id}</b><br>Produk: <b>${o.produk}</b><br>Paket: <b>${o.paket}</b><br>Total: <b>${rupiah(o.total)}</b><br>Status: <span class="statuspill ${statusClass(o.status)}">${o.status}</span>`}
async function loadRecent(){const {data}=await supabase.from("orders").select("*").order("created_at",{ascending:false}).limit(10);$("recentBody").innerHTML=(data||[]).map(o=>`<tr><td>${mask(o.order_id)}</td><td>${o.produk}</td><td>${o.paket}</td><td><span class="statuspill ${statusClass(o.status)}">${o.status}</span></td></tr>`).join("")||"<tr><td colspan='4'>Belum ada order</td></tr>";$("recentUpdated").textContent="Update "+new Date().toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"})}
function saveLocal(o){let arr=JSON.parse(localStorage.getItem("gs_orders")||"[]");const idx=arr.findIndex(x=>x.order_id===o.order_id);if(idx>=0)arr[idx]=o;else arr.unshift(o);localStorage.setItem("gs_orders",JSON.stringify(arr.slice(0,30)));renderHistory()}
function renderHistory(){const arr=JSON.parse(localStorage.getItem("gs_orders")||"[]");$("historyList").innerHTML=arr.length?arr.map(o=>`<div class="item"><b>${o.produk}</b><br>Order ID: <b>${o.order_id}</b><br>Paket: <b>${o.paket}</b><br>Total: <b>${rupiah(o.total)}</b><br>Status: <span class="statuspill ${statusClass(o.status)}">${o.status}</span></div>`).join(""):"Belum ada riwayat di browser ini."}
function go(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth"});closeDrawer()}
function openDrawer(){$("drawer").classList.add("show");$("overlay").classList.add("show")}
function closeDrawer(){$("drawer").classList.remove("show");$("overlay").classList.remove("show")}
function makeParticles(){const box=$("particles");for(let i=0;i<24;i++){const d=document.createElement("i");d.style.left=Math.random()*100+"%";d.style.top=Math.random()*100+"%";d.style.animationDelay=Math.random()*5+"s";box.appendChild(d)}}
function updateCountdown(){const end=new Date(getSetting("promo_end","2026-05-19 23:59:59")).getTime();const diff=Math.max(0,end-Date.now());const h=Math.floor(diff/3600000),m=Math.floor(diff%3600000/60000),s=Math.floor(diff%60000/1000);$("countdownTimer").textContent=[h,m,s].map(x=>String(x).padStart(2,"0")).join(":")}
$("drawerBtn").onclick=openDrawer;$("closeDrawer").onclick=closeDrawer;$("overlay").onclick=closeDrawer;$("homeBtn").onclick=()=>window.scrollTo({top:0,behavior:"smooth"});document.querySelectorAll("[data-go]").forEach(el=>el.onclick=()=>go(el.dataset.go));$("searchInput").oninput=applyFilter;$("closeDetail").onclick=()=>$("detailModal").classList.remove("show");$("closePay").onclick=()=>$("payModal").classList.remove("show");document.querySelectorAll(".plan").forEach(btn=>btn.onclick=()=>{selectedPlan=Number(btn.dataset.plan);document.querySelectorAll(".plan").forEach(b=>b.classList.remove("active"));btn.classList.add("active");updateSummary()});document.querySelectorAll(".pay").forEach(btn=>btn.onclick=()=>{selectedPay=btn.dataset.pay;document.querySelectorAll(".pay").forEach(b=>b.classList.remove("active"));btn.classList.add("active");updateSummary()});$("checkoutBtn").onclick=checkout;$("paidBtn").onclick=markPaid;$("copyPay").onclick=()=>copy($("payNumber").value);$("trackBtn").onclick=trackOrder;$("warrantyBtn").onclick=checkWarranty;$("askProductBtn").onclick=()=>{if(!selected)return;window.open(`https://wa.me/${waNumber}?text=${encodeURIComponent("Halo kak, saya mau tanya produk "+selected.name)}`,"_blank")};$("normalView").onclick=()=>{document.body.classList.remove("compact");$("normalView").classList.add("active");$("compactView").classList.remove("active")};$("compactView").onclick=()=>{document.body.classList.add("compact");$("compactView").classList.add("active");$("normalView").classList.remove("active")};makeParticles();load();setInterval(updateCountdown,1000);setInterval(load,30000);window.addEventListener("load",()=>setTimeout(()=>$("loader").classList.add("hide"),800));
